name: Deploy app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - run: docker run -e CI=true mikkometso/todo-app:latest npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: todo-app
          environment_name: Todoapp-env
          existing_bucket_name: elasticbeanstalk:eu-north-1:441431622552
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
